# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the TypeScript project
RUN npm run build

# Expose MCP server via stdio, so no ports are exposed

# Set default command
CMD ["node", "dist/index.js"]
